openapi: 3.0.0
info:
  title: Tax API
  version: 1.0.0
paths:
  /taxreturns:
    get:
      summary: Get all tax returns
      responses:
        '200':
          description: A list of tax returns
